import { MdView } from "../../../components/mdView";
import s from "./AboutPage.module.sass";
import banner from '../../../assets/img/suitok_banner.jpg'

export const AboutPage = () => {
    const mdStr =
        "# Suitok - Decentralized Platform for Video Creators\n**Suitok** is an innovative decentralized Web3 application designed to elevate the interaction between video creators and their audience. We have developed a platform that allows users to upload, store, and share video content using advanced blockchain technology powered by the **Walrus** protocol.\n## How does it work?\nOur project utilizes a decentralized infrastructure where all video files are uploaded and stored in **Walrus** nodes, ensuring data security, resilience, and independence. Through the **Sui Domain Name Service**, we have integrated a unique domain name for our project: **suitok.walrus.site**. This allows users to access the platform and content directly via Web3 technologies, offering maximum decentralization and transparency.\nAll site files are publicly accessible via the link [www.suitok.walrus.site](https://suitok.walrus.site), and the source code is open to everyone. You can review it on our GitHub repository at [github.suitokdev](https://github.com/suitokdev/suitok)\n## Key features of Suitok:\n-   **Decentralized storage**: Videos uploaded by users are stored across Walrus nodes, eliminating dependency on centralized servers.\n-   **Sui integration**: We plan to leverage Sui smart contracts to enhance data management, recommendations, and content interaction.\n-   **Creator monetization**: We are developing a reward system for content creators, to be integrated with the Sui protocol, providing new opportunities for content monetization and audience engagement.\n-   **Decentralized domains**: Suitok employs blockchain-based domain registration through Walrus, ensuring full autonomy and resilience for the site.\n## Why does this matter?\nWe are building a platform that supports the principles of decentralization, democratizing access to data storage and video content interaction. In a world where data is becoming increasingly centralized and controlled, Suitok represents a new chapter in media platforms, where users maintain control over their content.\n## What's next?\nSuitok is actively working on implementing a smart voting and donation system for users. We aim to create a fair and transparent monetization framework where video creators are rewarded for their contributions, and users can directly influence the popularity of videos through blockchain tools.\n## Join us!\nWe invite everyone to explore the possibilities of our platform and contribute to shaping a decentralized future for video content. Join Suitok today and be a part of the Web3 revolution!\nStay connected with us on [Telegram](https://t.me/suitok) and [Twitter](https://x.com/Suitokofficial) for updates! Exciting things are coming soon, including the launch of our token and community **competitions** that will reward active members for their contributions to the protocol. Don't miss out—be an early participant and help shape the future of decentralized video platforms!";

    return (
        <div className={s.aboutPage}>
            <img src={banner} alt="Suitok" />
            <MdView md={mdStr} />
        </div>
    );
};
